Lint: script + zig formatting

diff --git a/dev/bin/pgbuild b/dev/bin/pgbuild
--- a/dev/bin/pgbuild
+++ b/dev/bin/pgbuild
@@ -36,44 +36,44 @@ POSTGRES_BRANCH=${POSTGRES_BRANCH:-"REL_16_STABLE"}
 
 POSITIONAL_ARGS=()
 while [[ $# -gt 0 ]]; do
-  case $1 in
-    -h)
-      echo "$USAGE"
-      exit 0
-      ;;
-    --repo | -r)
-      POSTGRES_REPO="$2"
-      shift 2
-      ;;
-    -b | --branch)
-      POSTGRES_BRANCH="$2"
-      shift 2
-      ;;
-    *)
-      POSITIONAL_ARGS+=("$1") # save positional arg
-      shift # past argument
-      ;;
-  esac
+	case $1 in
+		-h)
+			echo "$USAGE"
+			exit 0
+			;;
+		--repo | -r)
+			POSTGRES_REPO="$2"
+			shift 2
+			;;
+		-b | --branch)
+			POSTGRES_BRANCH="$2"
+			shift 2
+			;;
+		*)
+			POSITIONAL_ARGS+=("$1") # save positional arg
+			shift                   # past argument
+			;;
+	esac
 done
 set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters
 
 clone() {
-  echo "Downloading postgres source from $POSTGRES_REPO"
+	echo "Downloading postgres source from $POSTGRES_REPO"
 
-  if [ -d "$PG_SRC_DIR" ] && [ -n "$(ls -A "$PG_SRC_DIR")" ]; then
-    echo "The directory $PG_SRC_DIR already exists and is not empty. Aborting."
-    return 0
-  fi
+	if [ -d "$PG_SRC_DIR" ] && [ -n "$(ls -A "$PG_SRC_DIR")" ]; then
+		echo "The directory $PG_SRC_DIR already exists and is not empty. Aborting."
+		return 0
+	fi
 
-  mkdir -p "$(dirname "$PG_SRC_DIR")"
-  git clone --single-branch -b "$POSTGRES_BRANCH" "$POSTGRES_REPO" "$PG_SRC_DIR"
+	mkdir -p "$(dirname "$PG_SRC_DIR")"
+	git clone --single-branch -b "$POSTGRES_BRANCH" "$POSTGRES_REPO" "$PG_SRC_DIR"
 }
 
 patch() {
-  # The meson scripts assume that clang is part of the LLVM suite, which is used when
-  # enabling the jit build (which we do). 
-  # Unfortunately the is not always the case. We work around this by patching the build scripts:
-  git -C "$PG_SRC_DIR" apply - <<EOF
+	# The meson scripts assume that clang is part of the LLVM suite, which is used when
+	# enabling the jit build (which we do).
+	# Unfortunately the is not always the case. We work around this by patching the build scripts:
+	git -C "$PG_SRC_DIR" apply - <<EOF
 diff --git a/meson.build b/meson.build
 index 6804f941be..d62142c8f7 100644
 --- a/meson.build
@@ -91,12 +91,12 @@ EOF
 }
 
 configure() {
-  echo "Configuring postgres build"
+	echo "Configuring postgres build"
 
-  patch
+	patch
 
-  meson setup "$PG_BUILD_DIR" "$PG_SRC_DIR" \
-    --debug \
+	meson setup "$PG_BUILD_DIR" "$PG_SRC_DIR" \
+		--debug \
 		-Dprefix="${PG_INSTALL_DIR}" \
 		-Dbindir="${PG_INSTALL_DIR}/bin" \
 		-Ddatadir="${PG_INSTALL_DIR}/share" \
@@ -121,13 +121,13 @@ configure() {
 }
 
 build() {
-  echo "Building postgres"
+	echo "Building postgres"
 
 	ninja -C "$PG_BUILD_DIR"
 }
 
 install() {
-  echo "Installing postgres to $PG_INSTALL_DIR"
+	echo "Installing postgres to $PG_INSTALL_DIR"
 
 	mkdir -p "${PG_INSTALL_DIR}"
 	ninja -C "${PG_BUILD_DIR}" install
@@ -136,28 +136,28 @@ install() {
 # The first argument determines the function to run. If no argument is given we run all commands in order:
 
 if [ -z "$1" ]; then
-  clone && configure && build && install
-  exit 0
+	clone && configure && build && install
+	exit 0
 fi
 
 case $1 in
-  clone)
-    clone
-    ;;
-  patch)
-    patch
-    ;;
-  configure)
-    configure
-    ;;
-  build)
-    build
-    ;;
-  install)
-    install
-    ;;
-  *)
-    echo "Usage: $0 {clone|configure|build|install}"
-    exit 1
-    ;;
+	clone)
+		clone
+		;;
+	patch)
+		patch
+		;;
+	configure)
+		configure
+		;;
+	build)
+		build
+		;;
+	install)
+		install
+		;;
+	*)
+		echo "Usage: $0 {clone|configure|build|install}"
+		exit 1
+		;;
 esac
diff --git a/dev/bin/pgstart b/dev/bin/pgstart
--- a/dev/bin/pgstart
+++ b/dev/bin/pgstart
@@ -8,7 +8,7 @@ eval "$(pgenv "$@")"
 
 echo "Starting PostgreSQL cluster $PG_CLUSTER_NAME"
 pg_ctl -D "$PG_CLUSTER_DATA_DIR" -l "$PG_CLUSTER_LOG_FILE" start || {
-  echo "Failed to start PostgreSQL"
-  cat "$PG_CLUSTER_LOG_FILE"
-  exit 1
+	echo "Failed to start PostgreSQL"
+	cat "$PG_CLUSTER_LOG_FILE"
+	exit 1
 }
diff --git a/dev/bin/ziglocal b/dev/bin/ziglocal
--- a/dev/bin/ziglocal
+++ b/dev/bin/ziglocal
@@ -32,73 +32,73 @@ ZIG_COMMIT=${ZIG_COMMIT:-""}
 
 POSITIONAL_ARGS=()
 while [[ $# -gt 0 ]]; do
-  case $1 in
-    -h)
-      echo "$USAGE"
-      exit 0
-      ;;
-    --repo | -r)
-      ZIG_REPO="$2"
-      shift 2
-      ;;
-    -b | --branch)
-      ZIG_BRANCH="$2"
-      shift 2
-      ;;
-    --commit)
-      ZIG_COMMIT="$2"
-      shift 2
-      ;;
-    *)
-      POSITIONAL_ARGS+=("$1") # save positional arg
-      shift # past argument
-      ;;
-  esac
+	case $1 in
+		-h)
+			echo "$USAGE"
+			exit 0
+			;;
+		--repo | -r)
+			ZIG_REPO="$2"
+			shift 2
+			;;
+		-b | --branch)
+			ZIG_BRANCH="$2"
+			shift 2
+			;;
+		--commit)
+			ZIG_COMMIT="$2"
+			shift 2
+			;;
+		*)
+			POSITIONAL_ARGS+=("$1") # save positional arg
+			shift                   # past argument
+			;;
+	esac
 done
 set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters
 
 clone() {
-  echo "Checkout $ZIG_REPO"
+	echo "Checkout $ZIG_REPO"
 
-  if [ -d "$ZIG_SRC_DIR" ] && [ -n "$(ls -A "$ZIG_SRC_DIR")" ]; then
-    echo "The directory '$ZIG_SRC_DIR' already exists and is not empty. Aborting."
-    return 0
-  fi
+	if [ -d "$ZIG_SRC_DIR" ] && [ -n "$(ls -A "$ZIG_SRC_DIR")" ]; then
+		echo "The directory '$ZIG_SRC_DIR' already exists and is not empty. Aborting."
+		return 0
+	fi
 
-  mkdir -p "$(dirname "$ZIG_SRC_DIR")"
-  git clone --single-branch -b "$ZIG_BRANCH" "$ZIG_REPO" "$ZIG_SRC_DIR"
+	mkdir -p "$(dirname "$ZIG_SRC_DIR")"
+	git clone --single-branch -b "$ZIG_BRANCH" "$ZIG_REPO" "$ZIG_SRC_DIR"
 
-  if [ -n "$ZIG_COMMIT" ]; then
-    git -C "$ZIG_SRC_DIR" checkout "$ZIG_COMMIT"
-  fi
+	if [ -n "$ZIG_COMMIT" ]; then
+		git -C "$ZIG_SRC_DIR" checkout "$ZIG_COMMIT"
+	fi
 }
 
 configure() {
-  mkdir -p "$ZIG_SRC_DIR/build"
-  cmake -B "$ZIG_SRC_DIR/build" -S "$ZIG_SRC_DIR" -G Ninja -DCMAKE_BUILD_TYPE=Debug
+	mkdir -p "$ZIG_SRC_DIR/build"
+	cmake -B "$ZIG_SRC_DIR/build" -S "$ZIG_SRC_DIR" -G Ninja -DCMAKE_BUILD_TYPE=Debug
 }
 
 build() {
-  ninja -C "$ZIG_SRC_DIR/build"
+	ninja -C "$ZIG_SRC_DIR/build"
 }
 
 if [ -z "$1" ]; then
-  clone && configure && build
-  exit 0
+	clone && configure && build
+	exit 0
 fi
 
 case $1 in
-  clone)
-    clone
-    ;;
-  configure)
-    configure
-    ;;
-  build)
-    build
-    ;;
-  *)
-    echo "Usage: $0 {clone|configure|build|install}"
-    exit 1
-    ;;
+	clone)
+		clone
+		;;
+	configure)
+		configure
+		;;
+	build)
+		build
+		;;
+	*)
+		echo "Usage: $0 {clone|configure|build|install}"
+		exit 1
+		;;
 esac
