Maintenance: Add Linters (#28)
Add code formatters and linters to the pre-commit hook and CI tests:
- check github actions
- shellcheck to lint for bad practices in shell scripts
- shfmt to require consistent formatting (tabs, indent case)
- zig fmt checks

Remove unused TOML and YAML file linters.

diff --git a/dev/bin/pginit b/dev/bin/pginit
--- a/dev/bin/pginit
+++ b/dev/bin/pginit
@@ -24,41 +24,41 @@ postgres_conf=
 POSITIONAL_ARGS=()
 
 while [[ $# -gt 0 ]]; do
-  case $1 in
-    -h)
-      echo "$USAGE"
-      exit 0
-      ;;
-    -p)
-      port="$2"
-      shift 2
-      ;;
-    -s)
-      if [ -n "$shared_preload_libraries" ]; then
-        shared_preload_libraries="$shared_preload_libraries,$2"
-      else
-        shared_preload_libraries="$2"
-      fi
-      shift 2
-      ;;
-    -i)
-      init_path="$2"
-      shift 2
-      ;;
-    -c)
-      postgres_conf="$2"
-      shift 2
-      ;;
-    -*|--*)
-      echo "Unknown option $1"
-      echo "$USAGE"
-      exit 1
-      ;;
-    *)
-      POSITIONAL_ARGS+=("$1") # save positional arg
-      shift # past argument
-      ;;
-  esac
+	case $1 in
+		-h)
+			echo "$USAGE"
+			exit 0
+			;;
+		-p)
+			port="$2"
+			shift 2
+			;;
+		-s)
+			if [ -n "$shared_preload_libraries" ]; then
+				shared_preload_libraries="$shared_preload_libraries,$2"
+			else
+				shared_preload_libraries="$2"
+			fi
+			shift 2
+			;;
+		-i)
+			init_path="$2"
+			shift 2
+			;;
+		-c)
+			postgres_conf="$2"
+			shift 2
+			;;
+		--* | -*)
+			echo "Unknown option $1"
+			echo "$USAGE"
+			exit 1
+			;;
+		*)
+			POSITIONAL_ARGS+=("$1") # save positional arg
+			shift                   # past argument
+			;;
+	esac
 done
 set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters
 
@@ -83,36 +83,36 @@ log_dir=$cluster_dir/log
 log_file=$log_dir/server.log
 
 # create the database
-mkdir -p $cluster_dir
-mkdir -p $data_dir
-mkdir -p $log_dir
-pg_ctl initdb -D $data_dir -o "--encoding=UTF8"
+mkdir -p "$cluster_dir"
+mkdir -p "$data_dir"
+mkdir -p "$log_dir"
+pg_ctl initdb -D "$data_dir" -o "--encoding=UTF8"
 
 # create database user
 date
-pg_ctl -t 60 -D $data_dir -l $log_file start || {
-  echo "Failed to start PostgreSQL"
-  date
-  cat $log_file
-  exit 1
+pg_ctl -t 60 -D "$data_dir" -l "$log_file" start || {
+	echo "Failed to start PostgreSQL"
+	date
+	cat "$log_file"
+	exit 1
 }
 
 # createdb $database
-createuser -d -e -i -l -r -s $user
+createuser -d -e -i -l -r -s "$user"
 if [ -n "$init_path" ]; then
-  psql -U $user -d $database < $init_path/*.sql
+	psql -U "$user" -d "$database" <"$init_path"/*.sql
 fi
 
-pg_ctl -D $data_dir stop
+pg_ctl -D "$data_dir" stop
 
 # update postgresql.conf
 if [ -n "$postgres_conf" ]; then
-  cp $postgres_conf/* $data_dir
+	cp "$postgres_conf"/* "$data_dir"
 fi
 if [ -n "$port" ]; then
-  echo "port=$port" >> $data_dir/postgresql.conf
+	echo "port=$port" >>"$data_dir/postgresql.conf"
 fi
 if [ -n "$shared_preload_libraries" ]; then
-  echo "shared_preload_libraries='$shared_preload_libraries'" >> $data_dir/postgresql.conf
+	echo "shared_preload_libraries='$shared_preload_libraries'" >>"$data_dir/postgresql.conf"
 fi
 # echo "max_prepared_transactions=100" >> ${datadir}/postgresql.conf
diff --git a/dev/bin/ziglocal b/dev/bin/ziglocal
--- a/dev/bin/ziglocal
+++ b/dev/bin/ziglocal
@@ -1,10 +1,17 @@
 #!/usr/bin/env bash
 
 USAGE="
-Usage: $0 <options>
+Usage: $0 <options> [command]
   -h: print this help message
   -r|--repo <repo>: git repository to clone postgres from.
   -b|--branch <branch>: branch to clone from the repository.
+
+If no command is given, the default is to clone, configure and build the project.
+
+Commands:
+  clone: clone the repository.
+  configure: configure the build.
+  build: build the project.
 
 Environment variables:
   WORKDIR: directory to store the files and installation.
@@ -12,7 +19,7 @@ Environment variables:
   ZIG_SRC_DIR: directory to store the zig source code.
 "
 
-set -x
+#set -x
 
 ROOTDIR=${PRJ_ROOT:-$(git rev-parse --show-toplevel)}
 WORKDIR=${WORKDIR:-"${ROOTDIR}/out"}
@@ -25,73 +32,73 @@ ZIG_COMMIT=${ZIG_COMMIT:-""}
 
 POSITIONAL_ARGS=()
 while [[ $# -gt 0 ]]; do
-  case $1 in
-    -h)
-      echo "$USAGE"
-      exit 0
-      ;;
-    --repo | -r)
-      ZIG_REPO="$2"
-      shift 2
-      ;;
-    -b | --branch)
-      ZIG_BRANCH="$2"
-      shift 2
-      ;;
-    --commit)
-      ZIG_COMMIT="$2"
-      shift 2
-      ;;
-    *)
-      POSITIONAL_ARGS+=("$1") # save positional arg
-      shift # past argument
-      ;;
-  esac
+	case $1 in
+		-h)
+			echo "$USAGE"
+			exit 0
+			;;
+		--repo | -r)
+			ZIG_REPO="$2"
+			shift 2
+			;;
+		-b | --branch)
+			ZIG_BRANCH="$2"
+			shift 2
+			;;
+		--commit)
+			ZIG_COMMIT="$2"
+			shift 2
+			;;
+		*)
+			POSITIONAL_ARGS+=("$1") # save positional arg
+			shift                   # past argument
+			;;
+	esac
 done
 set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters
 
 clone() {
-  echo "Checkout $ZIG_REPO"
+	echo "Checkout $ZIG_REPO"
 
-  if [ -d "$ZIG_SRC_DIR" ] && [ -n "$(ls -A $ZIG_SRC_DIR)" ]; then
-    echo "The directory $ZIG_SRC_DIR already exists and is not empty. Aborting."
-    return 0
-  fi
+	if [ -d "$ZIG_SRC_DIR" ] && [ -n "$(ls -A "$ZIG_SRC_DIR")" ]; then
+		echo "The directory '$ZIG_SRC_DIR' already exists and is not empty. Aborting."
+		return 0
+	fi
 
-  mkdir -p $(dirname $ZIG_SRC_DIR)
-  git clone --single-branch -b ${ZIG_BRANCH} ${ZIG_REPO} $ZIG_SRC_DIR
+	mkdir -p "$(dirname "$ZIG_SRC_DIR")"
+	git clone --single-branch -b "$ZIG_BRANCH" "$ZIG_REPO" "$ZIG_SRC_DIR"
 
-  if [ -n "$ZIG_COMMIT" ]; then
-    git -C $ZIG_SRC_DIR checkout $ZIG_COMMIT
-  fi
+	if [ -n "$ZIG_COMMIT" ]; then
+		git -C "$ZIG_SRC_DIR" checkout "$ZIG_COMMIT"
+	fi
 }
 
 configure() {
-  mkdir -p "$ZIG_SRC_DIR/build"
-  cmake -B "$ZIG_SRC_DIR/build" -S "$ZIG_SRC_DIR" -G Ninja -DCMAKE_BUILD_TYPE=Debug
+	mkdir -p "$ZIG_SRC_DIR/build"
+	cmake -B "$ZIG_SRC_DIR/build" -S "$ZIG_SRC_DIR" -G Ninja -DCMAKE_BUILD_TYPE=Debug
 }
 
 build() {
-  ninja -C "$ZIG_SRC_DIR/build"
+	ninja -C "$ZIG_SRC_DIR/build"
 }
 
 if [ -z "$1" ]; then
-  clone && configure && build
-  exit 0
+	clone && configure && build
+	exit 0
 fi
 
 case $1 in
-  clone)
-    clone
-    ;;
-  configure)
-    configure
-    ;;
-  build)
-    build
-    ;;
-  *)
-    echo "Usage: $0 {clone|configure|build|install}"
-    exit 1
-    ;;
+	clone)
+		clone
+		;;
+	configure)
+		configure
+		;;
+	build)
+		build
+		;;
+	*)
+		echo "Usage: $0 {clone|configure|build|install}"
+		exit 1
+		;;
 esac
